//
// Generated by JTB 1.3.2
//

package syntaxtree;

/**
 * Grammar production:
 * f0 -> ".ent" <IDENTIFIER> [ "," Constant() ]
 *       | ".aent" <IDENTIFIER> "," Constant()
 *       | ".mask" Expr() "," Expr()
 *       | ".fmask" Expr() "," Expr()
 *       | ".frame" Register() "," Expr() "," Register()
 *       | ".end" [ <IDENTIFIER> ]
 */
public class BlockDir implements Node {
   public NodeChoice f0;

   public BlockDir(NodeChoice n0) {
      f0 = n0;
   }

   public void accept(visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}

