//
// Generated by JTB 1.3.2
//

package syntaxtree;

/**
 * Grammar production:
 * f0 -> <IDENTIFIER_EQUAL>
 * f1 -> Expr()
 */
public class SymDef implements Node {
   public NodeToken f0;
   public Expr f1;

   public SymDef(NodeToken n0, Expr n1) {
      f0 = n0;
      f1 = n1;
   }

   public SymDef(Expr n0) {
      f0 = new NodeToken("=");
      f1 = n0;
   }

   public void accept(visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}

